package dev.oblac.eddi

import java.time.Instant
import kotlin.reflect.KClass

object Events {
    private val registry = mutableMapOf<KClass<out Event>, EventMeta<out Event>>()

    fun register(events: List<EventMeta<out Event>>) {
        events.forEach {
            registry[it.CLASS] = it
        }
    }

    @Suppress("UNCHECKED_CAST")
    fun <E : Event> metaOf(event: E): EventMeta<E> =
        registry[event::class] as? EventMeta<E> ?: error("Event ${event::class.simpleName} is not registered")
}

/**
 * Each [Event] will have its own [EventMeta] implementation generated by KSP.
 */
interface EventMeta<E: Event> {
    val CLASS: KClass<out Event>
    val NAME: EventName
    fun refs(event: E): Array<Tag>
}

@JvmInline
value class EventName(val value: String) {
    companion object Companion {
        fun of(event: Event) = EventName(event::class.simpleName ?: error("Event class must have a simple name"))
        fun of(event: KClass<*>) = EventName(event.simpleName ?: error("Event class must have a simple name"))
    }
}

/**
 * Marker interface for Events.
 */
interface Event

fun Event.eventName(): EventName = EventName.of(this)

/**
 * Interface for event references.
 */
interface Tag {
    val name: EventName
    val seq: ULong
}

/**
 * Reference to an event.
 */
data class Ref(
    override val name: EventName,
    override val seq: ULong
) : Tag


data class EventEnvelope<E : Event>(
    val sequence: ULong,
    val correlationId: ULong,   // todo add CorrelationId value type
    val event: E,
    val eventName: EventName,
    val timestamp: Instant = Instant.now(),
)

/**
 * Marker interface for commands.
 */
interface Command
